{{- if .Values.kafka.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "toae-console.fullname" . }}-kafka-broker-config
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
    name: {{ include "toae-console.fullname" . }}-kafka-broker-config
data:
  {{- range $k, $v := .Values.kafka.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
