ARG DF_IMG_TAG=latest
ARG IMAGE_REPOSITORY=deepfenceio

FROM $IMAGE_REPOSITORY/steampipe:$DF_IMG_TAG AS steampipe

FROM golang:1.21-bookworm AS build

WORKDIR /home/toae/plugins/cloud-scanner
COPY plugins/cloud-scanner .
#RUN go build -o cloud_scanner .


FROM debian:bookworm-slim
MAINTAINER TOAE SECURITY Inc
LABEL toae.role=system

ENV CHECKPOINT_DISABLE=true \
    DF_TLS_ON="1" \
    MGMT_CONSOLE_PORT=443 \
    MGMT_CONSOLE_URL_SCHEMA=https \
    TOAE_KEY="" \
    DEEPFENCE_KEY=$TOAE_KEY \
    DF_ENABLE_CLOUD_NODE="true" \
    HOME_DIR="/home/toae" \
    COMPLIANCE_MOD_PATH="/opt/steampipe"

RUN apt-get update \
    && apt-get install -y --no-install-recommends bash git ca-certificates nano logrotate sudo supervisor \
    #&& apt-get install -y --no-install-recommends postgresql-client-15 \
    && useradd -rm -d /home/toae -s /bin/bash -g root -G sudo -u 1001 toae \
    && mkdir -p /opt/steampipe /var/log/toaed \
    && chown toae /opt/steampipe

# Installing FluentBit
#RUN mkdir -p /etc/td-agent-bit/ /root/fluentbit
#COPY tools/apache/fluentbit/* /etc/td-agent-bit/

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY etc/fenced_logrotate.conf /etc/logrotate.d/fenced_logrotate.conf
RUN chmod 600 /etc/logrotate.d/fenced_logrotate.conf

COPY start_cloud_agent.sh /usr/local/bin/start_agent
RUN chmod +x /usr/local/bin/start_agent
#COPY plugins/fluent-bit/build/bin/fluent-bit /opt/td-agent-bit/bin/

RUN chown -R toae:root /opt/ /home/toae /var/log /var/run/
#    && chown -R root:root /etc/td-agent-bit/ /root/fluentbit

WORKDIR /opt/steampipe

USER toae
COPY supervisord-cloud.conf /home/toae/supervisord.conf
COPY --from=steampipe /usr/local/bin/steampipe /usr/local/bin/steampipe

RUN steampipe service start \
    && steampipe plugin install steampipe \
    # plugin version should be in sync with Toae fork https://github.com/Sam12121/steampipe-plugin-aws
    && steampipe plugin install aws@0.118.1 gcp@0.43.0 azure@0.49.0 azuread@0.12.0 \
    && git clone https://github.com/turbot/steampipe-mod-aws-compliance.git --branch v0.79 --depth 1 \
    && git clone https://github.com/turbot/steampipe-mod-gcp-compliance.git --branch v0.21 --depth 1 \
    && git clone https://github.com/turbot/steampipe-mod-azure-compliance.git --branch v0.35 --depth 1 \
    && steampipe service stop

COPY toaed /bin/toaed

ENV VERSION=2.1.0 \
    PUBLISH_CLOUD_RESOURCES_INTERVAL_MINUTES=5 \
    FETCH_CLOUD_RESOURCES_INTERVAL_HOURS=12

EXPOSE 8080

COPY --from=steampipe /usr/local/bin/steampipe-plugin-aws.plugin /home/toae/.steampipe/plugins/hub.steampipe.io/plugins/turbot/aws@latest/steampipe-plugin-aws.plugin
COPY --from=steampipe /usr/local/bin/steampipe-plugin-gcp.plugin /home/toae/.steampipe/plugins/hub.steampipe.io/plugins/turbot/gcp@latest/steampipe-plugin-gcp.plugin
COPY --from=steampipe /usr/local/bin/steampipe-plugin-azure.plugin /home/toae/.steampipe/plugins/hub.steampipe.io/plugins/turbot/azure@latest/steampipe-plugin-azure.plugin
COPY --from=steampipe /usr/local/bin/steampipe-plugin-azuread.plugin /home/toae/.steampipe/plugins/hub.steampipe.io/plugins/turbot/azuread@latest/steampipe-plugin-azuread.plugin

# Create symbolic link for /home/deepfence
RUN ln -s /home/toae /home/deepfence

COPY --from=build /home/toae/plugins/cloud-scanner/cloud_scanner /home/toae/bin/cloud_scanner

USER root

RUN ln -s /usr/local/bin/cloud_scanner /usr/local/bin/cloud_compliance_scan \
    && apt-get -y remove git ca-certificates

USER toae

ENTRYPOINT ["/usr/local/bin/start_agent"]
