# Define ARG variables
ARG DF_IMG_TAG=latest
ARG IMAGE_REPOSITORY=deepfenceio

# Use base image for steampipe
FROM $IMAGE_REPOSITORY/steampipe:$DF_IMG_TAG AS steampipe

# Use golang base image for build
FROM golang:1.21-bookworm AS build

# Set the working directory for the build stage
WORKDIR /home/toae/plugins/cloud-scanner

# Copy cloud-scanner plugin source code
COPY plugins/cloud-scanner .

# Switch to Debian base image for the final image
FROM debian:bookworm-slim

# Maintainer information
LABEL maintainer="TOAE SECURITY Inc"
LABEL toae.role=system

# Define environment variables
ENV DEEPFENCE_KEY=$TOAE_KEY \
    HOME_DIR="/home/toae" \
    COMPLIANCE_MOD_PATH="/opt/steampipe"

# Update package repositories and install required packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        git \
        ca-certificates \
        nano \
        logrotate \
        sudo \
        openssl \
        nginx \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user 'toae' with sudo privileges
RUN useradd -rm -d /home/toae -s /bin/bash -g root -G sudo -u 1001 toae

# Grant sudo privileges to user 'toae' without password prompt
RUN echo 'toae ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/toae

# Generate self-signed SSL certificate and key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/nginx-selfsigned.key \
    -out /etc/nginx/ssl/nginx-selfsigned.crt \
    -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"

# Copy NGINX configuration files
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY default.conf.template /etc/nginx/sites-available/default.conf.template

# Copy entrypoint script
COPY start_cloud_agent.sh /entrypoint.sh

# Set permissions for entrypoint script
RUN chmod +x /entrypoint.sh

# Switch to non-root user 'toae'
USER toae

# Set the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]

# Command to run when the container starts
CMD ["/usr/local/bin/cloud_scanner"]
