---
{{- if eq "true" .Values.createToaeKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: toae-key
  labels:
    app: toae
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- if .Values.toaeKey }}
  toae-key: "{{ .Values.toaeKey | b64enc }}"
{{- else }}
  toae-key: ""
{{- end }}
{{- end }}
---