{{- if .Values.kafka.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "toae-console.fullname" . }}-secrets-kafka
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
    component: kafka
stringData:
  TOAE_KAFKA_BROKERS: "{{ include "toae-console.fullname" . }}-kafka-broker.{{ .Release.Namespace }}.svc:9092"
{{- end }}
