{{- if .Values.redis.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "toae-console.fullname" . }}-secrets-redis
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
    component: redis
stringData:
  TOAE_REDIS_DB_NUMBER: "0"
  TOAE_REDIS_PORT: "6379"
  TOAE_REDIS_HOST: {{ include "toae-console.fullname" . }}-redis
{{- end }}
