{{- if and (eq .Values.fileserver.create false) .Values.aws_s3_buckets.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "toae-console.fullname" . }}-secrets-fileserver
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
    component: file-server
stringData:
  TOAE_MINIO_HOST: "s3.amazonaws.com"
  TOAE_MINIO_SECURE: "true"
  TOAE_MINIO_DB_BUCKET: {{ .Values.aws_s3_buckets.vulnerability_db_bucket | quote }}
  TOAE_MINIO_BUCKET: {{ .Values.aws_s3_buckets.data_bucket | quote }}
  TOAE_MINIO_PASSWORD: {{ .Values.aws_s3_buckets.secret_access_key | quote }}
  TOAE_MINIO_USER: {{ .Values.aws_s3_buckets.access_key_id | quote }}
  TOAE_MINIO_REGION: {{.Values.aws_s3_buckets.region | quote }}
{{- end }}
