---
{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toae-agent.imagePullSecretName" . }}
  labels:
    {{- include "toae-agent.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ template "imagePullSecret" . }}"
{{- end }}
---
{{- if .Values.createToaeKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toae-agent.fullname" . }}-key
  labels:
    {{- include "toae-agent.labels" . | nindent 4 }}
type: Opaque
data:
  toae-key: {{ required "toaeKey is required" .Values.toaeKey | b64enc }}
{{- end }}
