{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "toae-console.serviceAccountName" . }}
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- if ( include "toae-console.imagePullSecretName" . ) }}
imagePullSecrets:
  - name: {{ include "toae-console.imagePullSecretName" . }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "toae-console.fullname" . }}
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "toae-console.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    {{- if .Values.serviceAccount.create }}
    name: {{ include "toae-console.serviceAccountName" . }}
    {{- else }}
    name: {{ .Values.serviceAccount.name }}
    {{- end }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "toae-console.serviceAccountName" . }}-role
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
