---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "toae-console.fullname" . }}-config"
  labels:
    {{- include "toae-console.labels" . | nindent 4 }}
    name: "{{ include "toae-console.fullname" . }}-config"
data:
  TOAE_DEBUG: "false"
  TOAE_SAAS_DEPLOYMENT: "false"
