name: Build & Publish images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: false
        type: string
  pull_request:
    branches:
      - v2
      - main

env:
  DF_IMG_TAG: ${{ inputs.tag || github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Cache golang modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Check disk space
        run: df . -h
      - 
        name: Free disk space
        run: |
          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
  
          echo "some packages purged"
      - 
        name: Check disk space
        run: |
          sudo dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head
          df . -h
          sudo du /usr/ -hx -d 4 --threshold=1G | sort -hr | head
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Check working space directory
        run: du ${GITHUB_WORKSPACE} -h -d 1
      - 
        name: Get more space
        run: |
          df . -h
          sudo rm -rf ${GITHUB_WORKSPACE}/.git
          df . -h
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Remove Unused Docker Resources
        run: |
          docker container prune -f
          docker image prune -f
          docker volume prune -f
      - name: Check Disk Space
        run: df -h

      - name: Build images
        run: |
          make
      - name: Push images
        run: |
          make publish
      - name: Output image tag
        run: echo "New image tag ${DF_IMG_TAG}" >> $GITHUB_STEP_SUMMARY