name: Deploy to GKE

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: false
        type: string
  workflow_run:
    workflows:
      - Build & Publish images
    types:
      - completed

env:
  DF_IMG_TAG: ${{ inputs.tag || github.sha }}
  GKE_CLUSTER: "autopilot-cluster-1"  # Replace with your GKE cluster name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install kubectl

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region=us-central1

      - name: Helm installer
        uses: Azure/setup-helm@v3

      - name: Install router
        run: |
          helm upgrade --install router $GITHUB_WORKSPACE/deployment-scripts/helm-charts/toae-router

      - name: Clean up console
        continue-on-error: true
        run: |
          helm delete console

      - name: Install console
        run: |
          helm upgrade --wait --install console $GITHUB_WORKSPACE/deployment-scripts/helm-charts/toae-console --set global.imageTag=${DF_IMG_TAG}